services:


  mongo_db:
    container_name: db_container
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - 27017:27017
    restart: always


  picture_service:
    image: flask_picture
    ports:
      - 3000:3000

  song_service:
    image: flask_song
    ports:
      - 8080:8080
    depends_on: 
      - mongo_db
  

  django_service:
    image: django_website
    ports:
      - 8000:8000
    depends_on: 
      - song_service
      - picture_service

